spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123
  mail:
    host: smtp.caminalta.com
    port: 25
    username: report@caminalta.com
    password: naltaopr$78_78@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.coyoapp.tinytask: DEBUG
